### ISSUE TITLE
How do I handle response timeout?

### ISSUE THREAD

**Issue by clockk** [KeunwooPark/rinse-url#15]
hello
I'm interested because it's an interesting library.

There is no exception handling for timeout in `rinseURL`.
In fact, the timeout option is not set in the axios.get request within the `getHTML` method.
As an example, the URL where timeout should occur is as follows:
(https://www.coupang.com/vp/products/7091024989?a=2)

have any plans to add this in the future?

**Comment by KeunwooPark** [comment]
Thanks for opening this issue. I will add a `timeout` option.

**Comment by KeunwooPark** [comment]
Please feel free to re-open this issue if the latest version fails to solve this problem.

**Comment by KeunwooPark** [comment]
I wonder why this link throws a timeout error.

**Comment by KeunwooPark** [comment]
Dear @kis0421 ,
I figured out the reason. #20 will fix the problem. 
From `v0.1.8`, the example link will work fine.

**Comment by clockk** [comment]
Dear @KeunwooPark  
oh.. It was a case where a request without a header could not receive a normal response.
Thank you for checking.
Also appreciate the quick resolution about the timeout option
